name: mlops-aishield
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # #  Your ML workflow goes here
          pip install -r requirement.txt
          python extraction_reference_implementation_mnist.py
          
          echo "## extraction implementationModel Metrics" > report.md
          #cat Attack_samples >> report.md
          #cat Defense_artifact >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          #cml-publish model_results.png --md >> report.md
          
          #cml-send-comment report.md
